window.YM_COUNTRIES = [
  { en: "Afghanistan", zh: "阿富汗" },
  { en: "Albania", zh: "阿尔巴尼亚" },
  { en: "Algeria", zh: "阿尔及利亚" },
  { en: "Andorra", zh: "安道尔" },
  { en: "Angola", zh: "安哥拉" },
  { en: "Antigua and Barbuda", zh: "安提瓜和巴布达" },
  { en: "Argentina", zh: "阿根廷" },
  { en: "Armenia", zh: "亚美尼亚" },
  { en: "Australia", zh: "澳大利亚" },
  { en: "Austria", zh: "奥地利" },
  { en: "Azerbaijan", zh: "阿塞拜疆" },
  { en: "Bahamas", zh: "巴哈马" },
  { en: "Bahrain", zh: "巴林" },
  { en: "Bangladesh", zh: "孟加拉国" },
  { en: "Barbados", zh: "巴巴多斯" },
  { en: "Belarus", zh: "白俄罗斯" },
  { en: "Belgium", zh: "比利时" },
  { en: "Belize", zh: "伯利兹" },
  { en: "Benin", zh: "贝宁" },
  { en: "Bhutan", zh: "不丹" },
  { en: "Bolivia", zh: "玻利维亚" },
  { en: "Bosnia and Herzegovina", zh: "波黑" },
  { en: "Botswana", zh: "博茨瓦纳" },
  { en: "Brazil", zh: "巴西" },
  { en: "Brunei", zh: "文莱" },
  { en: "Bulgaria", zh: "保加利亚" },
  { en: "Burkina Faso", zh: "布基纳法索" },
  { en: "Burundi", zh: "布隆迪" },
  { en: "Cabo Verde", zh: "佛得角" },
  { en: "Cambodia", zh: "柬埔寨" },
  { en: "Cameroon", zh: "喀麦隆" },
  { en: "Canada", zh: "加拿大" },
  { en: "Central African Republic", zh: "中非" },
  { en: "Chad", zh: "乍得" },
  { en: "Chile", zh: "智利" },
  { en: "China", zh: "中国" },
  { en: "Colombia", zh: "哥伦比亚" },
  { en: "Comoros", zh: "科摩罗" },
  { en: "Congo", zh: "刚果（布）" },
  { en: "Costa Rica", zh: "哥斯达黎加" },
  { en: "Côte d'Ivoire", zh: "科特迪瓦" },
  { en: "Croatia", zh: "克罗地亚" },
  { en: "Cuba", zh: "古巴" },
  { en: "Cyprus", zh: "塞浦路斯" },
  { en: "Czech Republic", zh: "捷克" },
  { en: "Democratic Republic of the Congo", zh: "刚果（金）" },
  { en: "Denmark", zh: "丹麦" },
  { en: "Djibouti", zh: "吉布提" },
  { en: "Dominica", zh: "多米尼克" },
  { en: "Dominican Republic", zh: "多米尼加" },
  { en: "Ecuador", zh: "厄瓜多尔" },
  { en: "Egypt", zh: "埃及" },
  { en: "El Salvador", zh: "萨尔瓦多" },
  { en: "Equatorial Guinea", zh: "赤道几内亚" },
  { en: "Eritrea", zh: "厄立特里亚" },
  { en: "Estonia", zh: "爱沙尼亚" },
  { en: "Eswatini", zh: "斯威士兰" },
  { en: "Ethiopia", zh: "埃塞俄比亚" },
  { en: "Fiji", zh: "斐济" },
  { en: "Finland", zh: "芬兰" },
  { en: "France", zh: "法国" },
  { en: "Gabon", zh: "加蓬" },
  { en: "Gambia", zh: "冈比亚" },
  { en: "Georgia", zh: "格鲁吉亚" },
  { en: "Germany", zh: "德国" },
  { en: "Ghana", zh: "加纳" },
  { en: "Greece", zh: "希腊" },
  { en: "Grenada", zh: "格林纳达" },
  { en: "Guatemala", zh: "危地马拉" },
  { en: "Guinea", zh: "几内亚" },
  { en: "Guinea-Bissau", zh: "几内亚比绍" },
  { en: "Guyana", zh: "圭亚那" },
  { en: "Haiti", zh: "海地" },
  { en: "Honduras", zh: "洪都拉斯" },
  { en: "Hong Kong SAR", zh: "中国香港" },
  { en: "Hungary", zh: "匈牙利" },
  { en: "Iceland", zh: "冰岛" },
  { en: "India", zh: "印度" },
  { en: "Indonesia", zh: "印度尼西亚" },
  { en: "Iran", zh: "伊朗" },
  { en: "Iraq", zh: "伊拉克" },
  { en: "Ireland", zh: "爱尔兰" },
  { en: "Israel", zh: "以色列" },
  { en: "Italy", zh: "意大利" },
  { en: "Jamaica", zh: "牙买加" },
  { en: "Japan", zh: "日本" },
  { en: "Jordan", zh: "约旦" },
  { en: "Kazakhstan", zh: "哈萨克斯坦" },
  { en: "Kenya", zh: "肯尼亚" },
  { en: "Kiribati", zh: "基里巴斯" },
  { en: "Kuwait", zh: "科威特" },
  { en: "Kyrgyzstan", zh: "吉尔吉斯斯坦" },
  { en: "Laos", zh: "老挝" },
  { en: "Latvia", zh: "拉脱维亚" },
  { en: "Lebanon", zh: "黎巴嫩" },
  { en: "Lesotho", zh: "莱索托" },
  { en: "Liberia", zh: "利比里亚" },
  { en: "Libya", zh: "利比亚" },
  { en: "Liechtenstein", zh: "列支敦士登" },
  { en: "Lithuania", zh: "立陶宛" },
  { en: "Luxembourg", zh: "卢森堡" },
  { en: "Macao SAR", zh: "中国澳门" },
  { en: "Madagascar", zh: "马达加斯加" },
  { en: "Malawi", zh: "马拉维" },
  { en: "Malaysia", zh: "马来西亚" },
  { en: "Maldives", zh: "马尔代夫" },
  { en: "Mali", zh: "马里" },
  { en: "Malta", zh: "马耳他" },
  { en: "Marshall Islands", zh: "马绍尔群岛" },
  { en: "Mauritania", zh: "毛里塔尼亚" },
  { en: "Mauritius", zh: "毛里求斯" },
  { en: "Mexico", zh: "墨西哥" },
  { en: "Micronesia", zh: "密克罗尼西亚" },
  { en: "Moldova", zh: "摩尔多瓦" },
  { en: "Monaco", zh: "摩纳哥" },
  { en: "Mongolia", zh: "蒙古" },
  { en: "Montenegro", zh: "黑山" },
  { en: "Morocco", zh: "摩洛哥" },
  { en: "Mozambique", zh: "莫桑比克" },
  { en: "Myanmar", zh: "缅甸" },
  { en: "Namibia", zh: "纳米比亚" },
  { en: "Nauru", zh: "瑙鲁" },
  { en: "Nepal", zh: "尼泊尔" },
  { en: "Netherlands", zh: "荷兰" },
  { en: "New Zealand", zh: "新西兰" },
  { en: "Nicaragua", zh: "尼加拉瓜" },
  { en: "Niger", zh: "尼日尔" },
  { en: "Nigeria", zh: "尼日利亚" },
  { en: "North Korea", zh: "朝鲜" },
  { en: "North Macedonia", zh: "北马其顿" },
  { en: "Norway", zh: "挪威" },
  { en: "Oman", zh: "阿曼" },
  { en: "Pakistan", zh: "巴基斯坦" },
  { en: "Palau", zh: "帕劳" },
  { en: "Palestine", zh: "巴勒斯坦" },
  { en: "Panama", zh: "巴拿马" },
  { en: "Papua New Guinea", zh: "巴布亚新几内亚" },
  { en: "Paraguay", zh: "巴拉圭" },
  { en: "Peru", zh: "秘鲁" },
  { en: "Philippines", zh: "菲律宾" },
  { en: "Poland", zh: "波兰" },
  { en: "Portugal", zh: "葡萄牙" },
  { en: "Qatar", zh: "卡塔尔" },
  { en: "Romania", zh: "罗马尼亚" },
  { en: "Russia", zh: "俄罗斯" },
  { en: "Rwanda", zh: "卢旺达" },
  { en: "Saint Kitts and Nevis", zh: "圣基茨和尼维斯" },
  { en: "Saint Lucia", zh: "圣卢西亚" },
  { en: "Saint Vincent and the Grenadines", zh: "圣文森特和格林纳丁斯" },
  { en: "Samoa", zh: "萨摩亚" },
  { en: "San Marino", zh: "圣马力诺" },
  { en: "Sao Tome and Principe", zh: "圣多美和普林西比" },
  { en: "Saudi Arabia", zh: "沙特阿拉伯" },
  { en: "Senegal", zh: "塞内加尔" },
  { en: "Serbia", zh: "塞尔维亚" },
  { en: "Seychelles", zh: "塞舌尔" },
  { en: "Sierra Leone", zh: "塞拉利昂" },
  { en: "Singapore", zh: "新加坡" },
  { en: "Slovakia", zh: "斯洛伐克" },
  { en: "Slovenia", zh: "斯洛文尼亚" },
  { en: "Solomon Islands", zh: "所罗门群岛" },
  { en: "Somalia", zh: "索马里" },
  { en: "South Africa", zh: "南非" },
  { en: "South Korea", zh: "韩国" },
  { en: "South Sudan", zh: "南苏丹" },
  { en: "Spain", zh: "西班牙" },
  { en: "Sri Lanka", zh: "斯里兰卡" },
  { en: "Sudan", zh: "苏丹" },
  { en: "Suriname", zh: "苏里南" },
  { en: "Sweden", zh: "瑞典" },
  { en: "Switzerland", zh: "瑞士" },
  { en: "Syria", zh: "叙利亚" },
  { en: "Taiwan", zh: "中国台湾" },
  { en: "Tajikistan", zh: "塔吉克斯坦" },
  { en: "Tanzania", zh: "坦桑尼亚" },
  { en: "Thailand", zh: "泰国" },
  { en: "Timor-Leste", zh: "东帝汶" },
  { en: "Togo", zh: "多哥" },
  { en: "Tonga", zh: "汤加" },
  { en: "Trinidad and Tobago", zh: "特立尼达和多巴哥" },
  { en: "Tunisia", zh: "突尼斯" },
  { en: "Turkey", zh: "土耳其" },
  { en: "Turkmenistan", zh: "土库曼斯坦" },
  { en: "Tuvalu", zh: "图瓦卢" },
  { en: "Uganda", zh: "乌干达" },
  { en: "Ukraine", zh: "乌克兰" },
  { en: "United Arab Emirates", zh: "阿联酋" },
  { en: "United Kingdom", zh: "英国" },
  { en: "United States", zh: "美国" },
  { en: "Uruguay", zh: "乌拉圭" },
  { en: "Uzbekistan", zh: "乌兹别克斯坦" },
  { en: "Vanuatu", zh: "瓦努阿图" },
  { en: "Vatican City", zh: "梵蒂冈" },
  { en: "Venezuela", zh: "委内瑞拉" },
  { en: "Vietnam", zh: "越南" },
  { en: "Yemen", zh: "也门" },
  { en: "Zambia", zh: "赞比亚" },
  { en: "Zimbabwe", zh: "津巴布韦" }
];
